import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = path.join(projectRoot, "static", "site.css");
const sources = [
  ["tokens", "styles/tokens.css"],
  ["base", "styles/base.css"],
  ["motion", "styles/motion.css"],
  ["components", "styles/hero.css"],
  ["components", "styles/program.css"],
  ["components", "styles/footer.css"],
  ["responsive", "styles/responsive.css"],
];

const layers = [...new Set(sources.map(([layer]) => layer))];
const output = [
  "/* Generated by scripts/build-css.mjs. Edit the files in styles/ instead. */",
  `@layer ${layers.join(", ")};`,
  ...sources.map(([layer, relativePath]) => {
    const source = readFileSync(path.join(projectRoot, relativePath), "utf8").trim();
    return `@layer ${layer} {\n${source}\n}`;
  }),
].join("\n\n") + "\n";

writeFileSync(outputPath, output, "utf8");
console.log(`Built ${path.relative(projectRoot, outputPath)} from ${sources.length} source files.`);
